package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/letzcode/k8s-eu-audit/internal/model"
)

// RenderHTML returns a self-contained HTML compliance report.
func RenderHTML(r model.ComplianceReport) string {
	var b strings.Builder

	b.WriteString(`<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>` + r.Metadata.Framework + ` Compliance Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
         background: #f8f9fa; color: #212529; padding: 2rem; }
  .container { max-width: 960px; margin: 0 auto; }
  h1 { font-size: 1.6rem; font-weight: 700; margin-bottom: 0.25rem; }
  .meta { color: #6c757d; font-size: 0.85rem; margin-bottom: 2rem; }
  .summary { display: flex; gap: 1rem; margin-bottom: 2rem; flex-wrap: wrap; }
  .card { background: #fff; border-radius: 8px; padding: 1.25rem 1.5rem;
          border: 1px solid #dee2e6; flex: 1; min-width: 140px; }
  .card .label { font-size: 0.75rem; text-transform: uppercase;
                 letter-spacing: .05em; color: #6c757d; margin-bottom: .4rem; }
  .card .value { font-size: 2rem; font-weight: 700; line-height: 1; }
  .score-pass { color: #198754; }
  .score-warn { color: #fd7e14; }
  .score-fail { color: #dc3545; }
  table { width: 100%; border-collapse: collapse; background: #fff;
          border-radius: 8px; overflow: hidden; border: 1px solid #dee2e6; }
  thead { background: #f1f3f5; }
  th, td { padding: .75rem 1rem; text-align: left; border-bottom: 1px solid #dee2e6; }
  th { font-size: .8rem; text-transform: uppercase; letter-spacing: .05em;
       color: #495057; font-weight: 600; }
  tr:last-child td { border-bottom: none; }
  tr:hover td { background: #f8f9fa; }
  .badge { display: inline-block; padding: .25em .6em; border-radius: 4px;
           font-size: .8rem; font-weight: 600; }
  .badge-pass { background: #d1e7dd; color: #0a3622; }
  .badge-warn { background: #fff3cd; color: #664d03; }
  .badge-fail { background: #f8d7da; color: #58151c; }
  .badge-skip { background: #e9ecef; color: #495057; }
  .sev-critical { color: #dc3545; font-weight: 600; }
  .sev-high     { color: #fd7e14; font-weight: 600; }
  .sev-medium   { color: #ffc107; }
  .sev-low      { color: #6c757d; }
  footer { margin-top: 2rem; color: #adb5bd; font-size: .8rem; text-align: center; }
</style>
</head>
<body>
<div class="container">
`)

	// Header
	b.WriteString(fmt.Sprintf(`  <h1>%s Compliance Report</h1>
  <div class="meta">
    Generated: %s &nbsp;|&nbsp;
    Cluster: %s &nbsp;|&nbsp;
    Scanners: %s
  </div>
`,
		r.Metadata.Framework,
		r.Metadata.GeneratedAt.Format(time.RFC1123),
		r.Metadata.ClusterName,
		strings.Join(r.Metadata.Scanners, ", "),
	))

	// Summary cards
	scoreClass := "score-fail"
	switch r.Summary.Status {
	case "PASS":
		scoreClass = "score-pass"
	case "WARN":
		scoreClass = "score-warn"
	}

	b.WriteString(fmt.Sprintf(`  <div class="summary">
    <div class="card">
      <div class="label">Overall Score</div>
      <div class="value %s">%.0f%%</div>
    </div>
    <div class="card">
      <div class="label">Status</div>
      <div class="value %s">%s</div>
    </div>
    <div class="card">
      <div class="label">Pass</div>
      <div class="value score-pass">%d</div>
    </div>
    <div class="card">
      <div class="label">Warn</div>
      <div class="value score-warn">%d</div>
    </div>
    <div class="card">
      <div class="label">Fail</div>
      <div class="value score-fail">%d</div>
    </div>
    <div class="card">
      <div class="label">Skip</div>
      <div class="value">%d</div>
    </div>
  </div>
`,
		scoreClass, r.Summary.OverallScore,
		scoreClass, r.Summary.Status,
		r.Summary.TotalPass, r.Summary.TotalWarn,
		r.Summary.TotalFail, r.Summary.TotalSkip,
	))

	// Controls table
	b.WriteString(`  <table>
    <thead>
      <tr>
        <th>Article</th>
        <th>Requirement</th>
        <th>Severity</th>
        <th>Score</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
`)

	for _, cr := range r.Controls {
		badgeClass := "badge-skip"
		switch cr.Status {
		case "PASS":
			badgeClass = "badge-pass"
		case "WARN":
			badgeClass = "badge-warn"
		case "FAIL":
			badgeClass = "badge-fail"
		}

		sevClass := "sev-medium"
		switch cr.Control.Severity {
		case "CRITICAL":
			sevClass = "sev-critical"
		case "HIGH":
			sevClass = "sev-high"
		case "LOW":
			sevClass = "sev-low"
		}

		b.WriteString(fmt.Sprintf(`      <tr>
        <td>%s</td>
        <td>%s</td>
        <td class="%s">%s</td>
        <td>%.0f%%</td>
        <td><span class="badge %s">%s</span></td>
      </tr>
`,
			htmlEsc(cr.Control.Article),
			htmlEsc(cr.Control.Name),
			sevClass, cr.Control.Severity,
			cr.Score,
			badgeClass, cr.Status,
		))
	}

	b.WriteString(`    </tbody>
  </table>
  <footer>Generated by k8s-eu-audit &mdash; <a href="https://github.com/letzcode/k8s-eu-audit">github.com/letzcode/k8s-eu-audit</a></footer>
</div>
</body>
</html>
`)

	return b.String()
}

func htmlEsc(s string) string {
	s = strings.ReplaceAll(s, "&", "&amp;")
	s = strings.ReplaceAll(s, "<", "&lt;")
	s = strings.ReplaceAll(s, ">", "&gt;")
	return s
}
