package report

import (
	"fmt"
	"strings"
	"time"

	"github.com/letzcode/k8s-eu-audit/internal/model"
)

// RenderMarkdown returns a Markdown compliance report.
func RenderMarkdown(r model.ComplianceReport) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# %s Compliance Report\n\n", r.Metadata.Framework))
	b.WriteString(fmt.Sprintf("**Generated:** %s  \n", r.Metadata.GeneratedAt.Format(time.RFC1123)))
	b.WriteString(fmt.Sprintf("**Cluster:** %s  \n", r.Metadata.ClusterName))
	b.WriteString(fmt.Sprintf("**Scanners:** %s  \n\n", strings.Join(r.Metadata.Scanners, ", ")))

	// Summary
	b.WriteString("## Summary\n\n")
	b.WriteString(fmt.Sprintf("| Metric | Value |\n|--------|-------|\n"))
	b.WriteString(fmt.Sprintf("| Overall Score | **%.0f%%** |\n", r.Summary.OverallScore))
	b.WriteString(fmt.Sprintf("| Status | **%s** |\n", r.Summary.Status))
	b.WriteString(fmt.Sprintf("| Pass | %d |\n", r.Summary.TotalPass))
	b.WriteString(fmt.Sprintf("| Warn | %d |\n", r.Summary.TotalWarn))
	b.WriteString(fmt.Sprintf("| Fail | %d |\n", r.Summary.TotalFail))
	b.WriteString(fmt.Sprintf("| Skip | %d |\n\n", r.Summary.TotalSkip))

	// Controls table
	b.WriteString("## Controls\n\n")
	b.WriteString("| Article | Requirement | Severity | Score | Status |\n")
	b.WriteString("|---------|-------------|----------|-------|--------|\n")

	for _, cr := range r.Controls {
		icon := statusIcon(cr.Status)
		b.WriteString(fmt.Sprintf("| %s | %s | %s | %.0f%% | %s %s |\n",
			cr.Control.Article,
			cr.Control.Name,
			cr.Control.Severity,
			cr.Score,
			icon, cr.Status,
		))
	}
	b.WriteString("\n")

	// Failed controls detail
	hasFails := false
	for _, cr := range r.Controls {
		if cr.Status == "FAIL" || cr.Status == "WARN" {
			if !hasFails {
				b.WriteString("## Findings Requiring Attention\n\n")
				hasFails = true
			}
			b.WriteString(fmt.Sprintf("### %s %s — %s\n\n",
				statusIcon(cr.Status), cr.Control.Article, cr.Control.Name))
			b.WriteString(fmt.Sprintf("**Score:** %.0f%%  **Severity:** %s  **Status:** %s\n\n",
				cr.Score, cr.Control.Severity, cr.Status))
			if cr.Control.Remediation != "" {
				b.WriteString(fmt.Sprintf("**Remediation:** %s\n\n", cr.Control.Remediation))
			}
		}
	}

	b.WriteString("---\n")
	b.WriteString("*Generated by [k8s-eu-audit](https://github.com/letzcode/k8s-eu-audit)*\n")

	return b.String()
}

func statusIcon(status string) string {
	switch status {
	case "PASS":
		return "✅"
	case "WARN":
		return "⚠️"
	case "FAIL":
		return "❌"
	default:
		return "–"
	}
}
