package report

import (
	"io"
	"strings"
	"text/template"
	"time"

	"github.com/letzcode/k8s-eu-audit/internal/model"
)

const mdTmpl = `# {{ .Metadata.Framework }} Compliance Report

**Cluster:** {{ .Metadata.ClusterName }}
**Generated:** {{ formatTime .Metadata.GeneratedAt }}
**Scanners:** {{ join .Metadata.Scanners }}
**Overall Score:** {{ printf "%.0f" .Summary.OverallScore }}% — {{ .Summary.Status }}

---

## Controls

| Article | Requirement | Score | Status |
|---------|-------------|------:|--------|
{{ range .Controls -}}
| ` + "`{{ .Control.Article }}`" + ` | {{ .Control.Name }} | {{ printf "%.0f" .Score }}% | {{ .Status }} |
{{ end }}
## Summary

| | Count |
|-|------:|
| ✓ PASS | {{ .Summary.TotalPass }} |
| ⚠ WARN | {{ .Summary.TotalWarn }} |
| ✗ FAIL | {{ .Summary.TotalFail }} |
| – SKIP | {{ .Summary.TotalSkip }} |

---

## Recommendations

{{ range recommendations .Controls -}}
### [{{ .Severity }}] {{ .Article }} — {{ .Title }}

**Score:** {{ printf "%.0f" .Score }}% | **Failing checks:** {{ .FailCount }}

{{ .Remediation }}

---
{{ end }}
*Generated by [k8s-eu-audit](https://github.com/letzcode/k8s-eu-audit). Not legal advice.*
`

// recEntry is a flat struct used inside the markdown template.
type recEntry struct {
	Article     string
	Title       string
	Severity    string
	Score       float64
	Remediation string
	FailCount   int
}

func WriteMarkdown(w io.Writer, r model.ComplianceReport) error {
	fm := template.FuncMap{
		"formatTime": func(t time.Time) string {
			return t.UTC().Format("2006-01-02 15:04 UTC")
		},
		"join": func(s []string) string {
			return strings.Join(s, ", ")
		},
		"recommendations": func(controls []model.ControlResult) []recEntry {
			var out []recEntry
			for _, cr := range controls {
				if len(cr.Recommendations) == 0 {
					continue
				}
				rec := cr.Recommendations[0]
				out = append(out, recEntry{
					Article:     rec.Article,
					Title:       rec.Title,
					Severity:    rec.Severity,
					Score:       cr.Score,
					Remediation: rec.Remediation,
					FailCount:   rec.FailCount,
				})
			}
			return out
		},
	}

	tmpl, err := template.New("md").Funcs(fm).Parse(mdTmpl)
	if err != nil {
		return err
	}
	return tmpl.Execute(w, r)
}
